### ISSUE TITLE
add an assert method to check no exception is thrown

### ISSUE THREAD

**Issue by rouliane** [puzzle-org/assert#1]
The goal would be to assert that all the code before the assertion is executed and no exception are thrown.

Here we usually do that with `$this->assertTrue(true)` or `$this->addToAssertionCount(1)` helpers, but a method like "assertNoExceptionIsThrown()" is more explicit and better document the developer will.

The method content could be only `$this->addToAssertionCount(1);`

**Comment by Niktux** [comment]
```assertNoExceptionIsThrown()``` is okay for me
